# FROM node:12

# WORKDIR /app

# COPY package.json /app

# RUN npm install

# COPY . /app

# CMD pm2 start app.js 

# EXPOSE 7120

FROM node:12-alpine AS BUILD_IMAGE

# couchbase sdk requirements
RUN apk update && apk add  curl bash python g++ make && rm -rf /var/cache/apk/*

# install node-prune (https://github.com/tj/node-prune)
RUN curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash -s -- -b /usr/local/bin

WORKDIR /app

COPY package.json  ./

# install dependencies
# RUN yarn --frozen-lockfile

COPY . .

# lint & test
# RUN yarn lint & yarn test

# build application
# RUN yarn build
RUN npm install
# remove development dependencies
RUN npm prune --production

# run node prune
RUN /usr/local/bin/node-prune

# # remove unused dependencies
# RUN rm -rf node_modules/rxjs/src/
# RUN rm -rf node_modules/rxjs/bundles/
# RUN rm -rf node_modules/rxjs/_esm5/
# RUN rm -rf node_modules/rxjs/_esm2015/
# RUN rm -rf node_modules/swagger-ui-dist/*.map
# RUN rm -rf node_modules/couchbase/src/

FROM node:12-alpine

WORKDIR /app

# copy from build image
# COPY --from=BUILD_IMAGE /app/dist ./dist
COPY --from=BUILD_IMAGE /app/node_modules ./node_modules

EXPOSE 7120

# CMD [ "node", "app.js" ]
CMD pm2 start app.js 