# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.0.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  install:
    executor: node/default
    steps:
      - checkout
      - run: npm install
  pull:
    executor: node/default
    steps:
      - checkout
      - run: git pull https://github.com/trieunguyenterralogic/Cloudcontroller-Backend-Clone.git circleci-project-setup
  build:
    executor: node/default
    steps:
      - checkout
      - run: npm next build

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  BE-Example:
    jobs:
      - install
      - pull: 
         requires:
            - install
      - build:
          requires:
            - pull 
